/* *
68.4- crete client post then server for database add 
68.5-load data client and auth user email for query load fetch url link then
server req.query.email then query object email for find singe email user get method
68.6----------->
                <--------JWT Token------>

1.https://www.npmjs.com/package/jsonwebtoken --> https://github.com/auth0/node-jsonwebtoken
2.ei tader website gelo ar detils jante parba ---> https://jwt.io/

<---> client side Login page aplai for JWT Token
3.server side install => npm i jsonwebtoken
4.server route for login page jwt token 
5.import kora lagbe ---> const jwt = require('jsonwebtoken');
<-----secreet-key-bananor-jonno----node-server-of kore-age-node-leke-enter-press-kore-tarpor-type-korete-hobe--->
6.--require('crypto').randomBytes(64).toString('hex')
7.env file access_token_secret-boro-hater-leke-tarpor = somon diye vscode take codea tion chare copy kore ane akane bosaba.

8.crate node server access token 
9.crate post user 
10.crate access token and send object access token client side 
11.access token = Create JWT Token, Get jwt token on client side
*/